# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  CI-main:
    name: CI-main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Tests
        id: test
        run: dotnet test --no-build --verbosity normal
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./test/Dockerfile
          push: true
          tags: |
            oswe/app:${{ github.sha }}
            oswe/app:latest
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} - ${{ job.status }}
          body: | 
            The job ${{ github.job }} in workflow ${{ github.workflow }} of repository ${{ github.repository }} - ${{ job.status }}.

            Commit: ${{ github.sha }}
            Commit Author: ${{ github.actor }}
            Commit Message: ${{ github.event.head_commit.message }}

            Test Status:
            ${{ steps.test.outcome == 'failure' && 'Some tests failed.' || 'All tests passed successfully.' }}

            For more details, visit the https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          to: ${{secrets.EMAIL_WORKERS}}
          from: Tech-trend-emporium

  CD-main:
    name: CD-main
    needs: CI-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
        env:
            PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      - name: Deploy to Ec2
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.USER_NAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            docker pull oswe/app:latest
            docker ps -q | xargs -r docker stop
            docker ps -a -q | xargs -r docker rm
            docker run -d -p 8080:8080 --name app oswe/app:latest
            docker images -q | grep -v -e $(docker images -q --filter "reference=oswe/app:latest") | xargs -r docker rmi
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} - ${{ job.status }}
          body: | 
            The job ${{ github.job }} in workflow ${{ github.workflow }} of repository ${{ github.repository }} - ${{ job.status }}.

            Commit: ${{ github.sha }}
            Commit Author: ${{ github.actor }}
            Commit Message: ${{ github.event.head_commit.message }}

            Test Status:
            ${{ steps.deploy.outcome == 'failure' && 'The deployment has failed.' || 'The deployment was successful.' }}

            For more details, visit the https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          to: ${{secrets.EMAIL_WORKERS}}
          from: Tech-trend-emporium


         